//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_items
    {
        public int id { get; set; }
        public int cart_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string image { get; set; }
        public int quantity { get; set; }
        public decimal original_price { get; set; }
        public decimal sale_price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
