//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_conditions
    {
        public int id { get; set; }
        public int coupon_id { get; set; }
        public string attribute { get; set; }
        public string @operator { get; set; }
        public string value { get; set; }
        public decimal discount_amount { get; set; }
        public string discount_type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual coupon coupon { get; set; }
    }
}
