//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string full_name { get; set; }
        public string phone_number { get; set; }
        public string shipping_address { get; set; }
        public string note { get; set; }
        public decimal subtotal_money { get; set; }
        public decimal shipping_fee { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> total_money { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
        public string shipping_method { get; set; }
        public string tracking_number { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> estimated_delivery_start_date { get; set; }
        public Nullable<System.DateTime> estimated_delivery_end_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual user user { get; set; }
    }
}
