//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.post_tags = new HashSet<post_tags>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string slug { get; set; }
        public string excerpt { get; set; }
        public string content { get; set; }
        public string thumbnail_url { get; set; }
        public int author_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> published_at { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual post_categories post_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_tags> post_tags { get; set; }
        public virtual user user { get; set; }
    }
}
