//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_tags
    {
        public int id { get; set; }
        public int post_id { get; set; }
        public int tag_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual post post { get; set; }
        public virtual tag tag { get; set; }
    }
}
