//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_items = new HashSet<cart_items>();
            this.order_items = new HashSet<order_items>();
            this.product_images = new HashSet<product_images>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public string slug { get; set; }
        public string thumbnail_url { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public string ingredients { get; set; }
        public string dosage { get; set; }
        public string contraindications { get; set; }
        public string packaging_details { get; set; }
        public Nullable<bool> prescription_required { get; set; }
        public decimal original_price { get; set; }
        public decimal sale_price { get; set; }
        public int stock_quantity { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual brand brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_images> product_images { get; set; }
    }
}
